### ISSUE TITLE
kpaas部署报错

### ISSUE THREAD

**Issue by luciferhs** [kplcloud/cloud-website#37]
[root@master kpaas]# kubectl logs kplcloud-669d79f464-9v24q -f
panic: Exception (403) Reason: "username or password not allowed"

goroutine 1 [running]:
github.com/kplcloud/kplcloud/cmd/server.run()
	/go/src/github.com/kplcloud/kplcloud/cmd/server/server.go:177 +0x7312
github.com/kplcloud/kplcloud/cmd/server.glob..func1(0x28bad00, 0xc00007eb40, 0x0, 0x6, 0x0, 0x0)
	/go/src/github.com/kplcloud/kplcloud/cmd/server/server.go:118 +0x20
github.com/spf13/cobra.(*Command).execute(0x28bad00, 0xc00007ea20, 0x6, 0x6, 0x28bad00, 0xc00007ea20)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x28baa80, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/kplcloud/kplcloud/cmd/server.Run()
	/go/src/github.com/kplcloud/kplcloud/cmd/server/server.go:138 +0x2d
main.main()
	/go/src/github.com/kplcloud/kplcloud/main.go:13 +0x20
请问，这里的的用户名或者密码是指的哪里的呢？

**Comment by icowan** [comment]
@luciferhs 应该是 rabbitmq 的用户名及密码错误
